all: exercice1 exercice2 exercice3 exercice4

exercice1: exercice1.c
	gcc -Wall -pedantic -ansi exercice1.c -o exercice1

exercice2: exercice2.c
	gcc -Wall -pedantic -ansi exercice2.c -o exercice2 

exercice3: exercice3.c
	gcc -Wall -pedantic -ansi exercice3.c -o exercice3
	
exercice4: exercice4.c
	gcc -Wall -pedantic -ansi exercice4.c -o exercice4