all: nl linked_list linked_imp

nl: nl.c
	gcc -Wall -pedantic -ansi nl.c -o nl

linked_list: linked_list.c
	gcc -Wall -pedantic -ansi linked_list.c -o linked_list

linked_imp: linked_imp.c
	gcc -Wall -pedantic -ansi linked_imp.c -o linked_imp